[package]
name = "diesel-1"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
diesel = { version = "2.0.0", features = ["postgres"] }

[[bin]]
name = "diesel-1"
path = "src/main.rs"
doc = false
