(function() {var implementors = {
"bitflags":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"bitflags/parser/struct.ParseError.html\" title=\"struct bitflags::parser::ParseError\">ParseError</a>"]],
"darling_core":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"darling_core/error/struct.Error.html\" title=\"struct darling_core::error::Error\">Error</a>"]],
"diesel":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"diesel/prelude/enum.ConnectionError.html\" title=\"enum diesel::prelude::ConnectionError\">ConnectionError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"diesel/result/enum.Error.html\" title=\"enum diesel::result::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"diesel/result/struct.DeserializeFieldError.html\" title=\"struct diesel::result::DeserializeFieldError\">DeserializeFieldError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"diesel/result/struct.EmptyChangeset.html\" title=\"struct diesel::result::EmptyChangeset\">EmptyChangeset</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"diesel/result/struct.UnexpectedEndOfRow.html\" title=\"struct diesel::result::UnexpectedEndOfRow\">UnexpectedEndOfRow</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"diesel/result/struct.UnexpectedNullError.html\" title=\"struct diesel::result::UnexpectedNullError\">UnexpectedNullError</a>"]],
"dotenvy":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"dotenvy/enum.Error.html\" title=\"enum dotenvy::Error\">Error</a>"]],
"either":[["impl&lt;L, R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt;<div class=\"where\">where\n    L: <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a>,\n    R: <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a>,</div>"]],
"proc_macro2":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"proc_macro2/struct.LexError.html\" title=\"struct proc_macro2::LexError\">LexError</a>"]],
"serde":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"serde/de/value/struct.Error.html\" title=\"struct serde::de::value::Error\">Error</a>"]],
"strsim":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"strsim/enum.StrSimError.html\" title=\"enum strsim::StrSimError\">StrSimError</a>"]],
"syn":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.79.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"syn/parse/struct.Error.html\" title=\"struct syn::parse::Error\">Error</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()